In [1]:
import torch
import numpy as np

# 1. Tensors

# Dimensional Tensors

In [2]:
v = torch.tensor([1,2,3,4,5,6])
print(v[1:4])

tensor([2, 3, 4])


In [3]:
f = torch.FloatTensor([1,2,3,4,5,6])
print(f.size())

torch.Size([6])


In [4]:
v.view(6,1) # 원래 값과 같은 차원이어야 함

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [10]:
v.view(5,1) # Error

RuntimeError: shape '[5, 1]' is invalid for input of size 6

In [13]:
v.view(3,2) # 원래 값과 같은 차원이어야 함

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [12]:
v.view(3,-1) # -1을 입력할 경우, 값을 알아서 채워줌

tensor([[1, 2],
        [3, 4],
        [5, 6]])

## Numpy - Torch 변환

In [6]:
a = np.array([1,2,3,4,5])
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


In [8]:
numpy_cnv  = tensor_cnv.numpy()
print(numpy_cnv)

[1 2 3 4 5]


# 2. Vector Operations

In [20]:
t_one = torch.tensor([1,2,3])
t_two= torch.tensor([1,2,3])
dot_product = torch.dot(t_one, t_two)

print(t_one + t_two)
print(t_one * t_two)
print(dot_product)

tensor([2, 4, 6])
tensor([1, 4, 9])
tensor(14)


In [22]:
torch.linspace(0, 10) # 0 ~ 10 사이의 같은 간격의 값을 출력

/var/folders/0_/7nng3dk94db81flkq5mljn_00000gn/T/ipykernel_6814/1619988884.py:1: UserWarning: Not providing a value for linspace's steps is deprecated and will throw a runtime error in a future release. This warning will appear only once per process. (Triggered internally at  ../aten/src/ATen/native/RangeFactories.cpp:23.)
  torch.linspace(0, 10)


tensor([ 0.0000,  0.1010,  0.2020,  0.3030,  0.4040,  0.5051,  0.6061,  0.7071,
         0.8081,  0.9091,  1.0101,  1.1111,  1.2121,  1.3131,  1.4141,  1.5152,
         1.6162,  1.7172,  1.8182,  1.9192,  2.0202,  2.1212,  2.2222,  2.3232,
         2.4242,  2.5253,  2.6263,  2.7273,  2.8283,  2.9293,  3.0303,  3.1313,
         3.2323,  3.3333,  3.4343,  3.5354,  3.6364,  3.7374,  3.8384,  3.9394,
         4.0404,  4.1414,  4.2424,  4.3434,  4.4444,  4.5455,  4.6465,  4.7475,
         4.8485,  4.9495,  5.0505,  5.1515,  5.2525,  5.3535,  5.4545,  5.5556,
         5.6566,  5.7576,  5.8586,  5.9596,  6.0606,  6.1616,  6.2626,  6.3636,
         6.4646,  6.5657,  6.6667,  6.7677,  6.8687,  6.9697,  7.0707,  7.1717,
         7.2727,  7.3737,  7.4747,  7.5758,  7.6768,  7.7778,  7.8788,  7.9798,
         8.0808,  8.1818,  8.2828,  8.3838,  8.4848,  8.5859,  8.6869,  8.7879,
         8.8889,  8.9899,  9.0909,  9.1919,  9.2929,  9.3939,  9.4950,  9.5960,
         9.6970,  9.7980,  9.8990, 10.00